services:
  timevat:
    container_name: fileScanner
    user: 0:0
    volumes:
      - /mnt/filesystem/storage/torrent:/torrent
    build:
      context: .
      dockerfile: Dockerfile # installs OpenTelemetry .NET Automatic Instrumentation
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: Europe/Copenhagen
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      ASPNETCORE_URLS: http://+:80
    restart: unless-stopped
    ports:
      - "7070:80"